calendar-37
skidunion/mai-calendar pull request #39
Opened 2024-05-25 21:25 UTC by CrazyCatGames

2024-05-25 21:27 UTC, skidunion requested changes

2024-05-25 21:27 UTC, skidunion commented on main/views.py
> +        week_number = 7
`n / 2`, `n / 2 + 1`

2024-05-25 21:27 UTC, skidunion commented on main/views.py
> +    return render(req, 'edit_timetable.html', context)
`get_template` важен, оставь

2024-05-25 21:30 UTC, CrazyCatGames commented on main/views.py
> +        week_number = 7
Есть ли в этом смысл, если учебных недель никак не может быть меньше 15 например?

2024-05-26 12:38 UTC, skidunion requested changes

2024-05-26 12:38 UTC, skidunion commented on main/templates/edit_timetable.html
> +                <div class="WeekDropdown__selector">Выберите неделю</div>
Тут нужно показывать выбранную неделю

2024-05-26 16:13 UTC, skidunion approved these changes

2024-05-26 16:14 UTC, merged